services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: chest_disease_api
    ports:
      - "8001:8000"
    volumes:
      - ./saved_model:/app/saved_model:ro
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: chest_disease_dashboard
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
    depends_on:
      - api
    volumes:
      - ./data/processed:/app/data/processed:ro
    restart: unless-stopped
